services:
  ibu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ibu-dashboard
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./docker/data/scraped_team_info:/ibu/Scraped_Team_Info
      - ./docker/data/scraped_teams_points:/ibu/Scraped_Teams_Points
      - ./docker/config:/ibu/config
      - ./docker/logs/:/ibu/logs
      - ./docker/notification_history/:/ibu/notification_history/
      - /etc/localtime:/etc/localtime:ro
